import React,{useEffect,useState} from 'react';
import {db,result,readResources,fileLink,submissionInput,checkFile,licenses,types} from './community';
import {safeUrl} from './config';
const cats=['Projects','Tools','Learning','Downloads','Recommendations','Other'];
function Notice({message}) {return message?<p className="community-notice" role="status">{message}</p>:null;}
function Field({label,name,value,onChange,area=false,...props}) {const Tag=area?'textarea':'input';return <label className="field"><span>{label}</span><Tag name={name} value={value} onChange={onChange} {...props}/></label>;}
export function CommunityHeader(){return <header><a className="brand" href="/">P<span className="green">3</span><span>PhoenixR3born<small>BUILD. LEARN. SHARE.</small></span></a><nav aria-label="Main"><a href="/">Collection</a><a href="/community">Community</a><a href="/account">Your space</a></nav></header>;}
function Resource({r,review=false,onReview}) {
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function download(){setBusy(true);setMessage('');try{const url=await fileLink(r);const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.click();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <article className="card"><div className="card-content"><div className="card-top"><span className="category-label">{r.category}</span>{r.category==='Projects'?<span className={`status-badge ${r.project_status}`}>{r.project_status==='completed'?'Completed':'In progress'}</span>:null}{review?<span className="category-label">{r.moderation_status}</span>:null}</div><h3><a href={`/resource/${r.id}`}>{r.title}</a></h3><p>{r.summary}</p><p className="resource-by">By <a href={`/u/${r.profiles?.username}`}>{r.profiles?.display_name || r.profiles?.username}</a></p><div className="actions">{safeUrl(r.website_url)?<a className="button" href={safeUrl(r.website_url)} target="_blank" rel="noopener noreferrer">Visit website</a>:null}{safeUrl(r.github_url)?<a className="secondary-button" href={safeUrl(r.github_url)} target="_blank" rel="noopener noreferrer">Read setup instructions</a>:null}{r.file_path?<button className="secondary-button" disabled={busy} onClick={download}>{busy?'Preparing…':'Download file'}</button>:null}</div>{review&&r.moderation_status!=='approved'?<div className="actions"><button className="button" onClick={()=>onReview(r,'approved')}>Approve</button><button className="secondary-button" onClick={()=>onReview(r,'rejected')}>Reject</button></div>:null}{review&&r.moderation_status==='approved'?<button className="secondary-button" onClick={()=>onReview(r,'rejected')}>Unpublish</button>:null}<Notice message={message}/></div></article>;
}
function Grid({rows,...props}) {return rows.length?<div className="grid community-grid">{rows.map(r=><Resource key={r.id} r={r} {...props}/>)}</div>:<div className="state"><h3>No resources here yet.</h3><p>Useful things start with someone sharing them.</p></div>;}
function Account({user}) {
 const [profile,setProfile]=useState({username:'',display_name:'',bio:''}),[existing,setExisting]=useState(false),[rows,setRows]=useState([]),[admin,setAdmin]=useState(false),[ready,setReady]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{await result(db.rpc('claim_first_moderator')).catch(() => false);const p=await result(db.from('profiles').select('*').eq('id',user.id).maybeSingle());if(p){setProfile(p);setExisting(true);}setAdmin(await result(db.rpc('moderator_status')));setRows(await readResources({author:user.id}));setReady(true);}catch(e){setMessage(e.message);}}
 useEffect(()=>{load();},[user.id]);
 async function save(e){e.preventDefault();setBusy(true);setMessage('');try{const data={username:profile.username.trim().toLowerCase(),display_name:profile.display_name.trim(),bio:profile.bio};if(existing)await result(db.from('profiles').update(data).eq('id',user.id));else await result(db.from('profiles').insert({id:user.id,...data}));setExisting(true);setMessage('Your public profile is saved.');}catch(e){setMessage(e.message.includes('duplicate')?'That username is already taken. Try another.':e.message);}finally{setBusy(false);}}
 return <><span className="eyebrow">YOUR SPACE</span><h1>Make yourself at home.</h1><p className="intro">Your profile is public. Your email stays private. New resources wait for review.</p><Notice message={message}/>{ready?<><form className="community-form" onSubmit={save}><h2>Your public profile</h2><Field label="Username" name="username" value={profile.username} onChange={e=>setProfile({...profile,username:e.target.value.toLowerCase()})} pattern="[a-z0-9][a-z0-9_]{2,29}" minLength={3} maxLength={30} required autoComplete="username"/><small>3 to 30 lowercase letters, numbers, or underscores.</small><Field label="Display name" value={profile.display_name} onChange={e=>setProfile({...profile,display_name:e.target.value})} required maxLength={60}/><Field label="A little about you" area value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})} maxLength={500}/><button className="button" disabled={busy}>{busy?'Saving…':'Save profile'}</button>{existing?<a className="text-link" href={`/u/${profile.username}`}>View public profile</a>:null}</form><div className="actions">{existing?<a className="button" href="/submit">Share something useful</a>:null}{admin?<a className="secondary-button" href="/review">Review submissions</a>:null}<button className="secondary-button" onClick={async()=>{await db.auth.signOut();location.assign('/account');}}>Sign out</button></div><h2>Your submissions</h2><Grid rows={rows}/>{rows.length?<p>Pending resources are visible only to you and moderators. To correct a submission, submit a revised version.</p>:null}</>:<p role="status">Loading your space…</p>}</>;
}
function SignIn(){const [email,setEmail]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);async function sign(e){e.preventDefault();setBusy(true);try{await result(db.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/account`}}));setMessage('Check your email for your sign-in link. Open it in this browser to finish.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <><span className="eyebrow">JOIN P3</span><h1>A space for what you know.</h1><p className="intro">Share your work, create a profile, and help someone learn. Sign in or create an account with an email link.</p><form className="community-form" onSubmit={sign}><Field label="Email address" type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" maxLength={254}/><button className="button" disabled={busy}>{busy?'Sending…':'Email me a sign-in link'}</button><small>No password to remember. Only your chosen profile information becomes public.</small><Notice message={message}/></form></>;
}
function Submit({user}){const [form,setForm]=useState({title:'',summary:'',description:'',category:'Learning',project_status:'in-progress',website_url:'',github_url:'',license:'See source license'}),[file,setFile]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[hasProfile,setHasProfile]=useState(null);
 useEffect(()=>{result(db.from('profiles').select('id').eq('id',user.id).maybeSingle()).then(p=>setHasProfile(!!p)).catch(e=>setMessage(e.message));},[user.id]);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 async function submit(e){e.preventDefault();setBusy(true);setMessage('');let path;try{const id=crypto.randomUUID();const input=submissionInput(form,user.id,id,file);if(file){const type=checkFile(file);path=input.file_path;await result(db.storage.from('community').upload(path,file,{contentType:type,upsert:false}));}await result(db.from('submissions').insert(input));setSent(true);setMessage('Submitted for review. Your file remains private until a moderator approves it.');}catch(e){if(path)await db.storage.from('community').remove([path]);setMessage(e.message);}finally{setBusy(false);}}
 if(hasProfile===false)return <><h1>First, introduce yourself.</h1><p>Create your profile before sharing a resource.</p><a className="button" href="/account">Create profile</a></>;
 if(hasProfile===null)return <p role="status">Checking your profile…</p>;
 return <><span className="eyebrow">CONTRIBUTE</span><h1>Share something useful.</h1><p className="intro">A project, a textbook, a helpful tool, or a resource worth passing on. Five submissions per day. Each one is reviewed.</p>{sent?<><Notice message={message}/><a className="button" href="/account">View your submissions</a></>:<form className="community-form wide" onSubmit={submit}><Field label="Title" name="title" value={form.title} onChange={change} required minLength={3} maxLength={100}/><Field label="Why someone needs this" area name="summary" value={form.summary} onChange={change} required minLength={10} maxLength={280}/><Field label="Description and instructions" area name="description" value={form.description} onChange={change} maxLength={20000}/><label className="field"><span>Category</span><select name="category" value={form.category} onChange={change}>{cats.map(c=><option key={c}>{c}</option>)}</select></label>{form.category==='Projects'?<label className="field"><span>Project status</span><select name="project_status" value={form.project_status} onChange={change}><option value="in-progress">In progress</option><option value="completed">Completed</option></select></label>:null}<Field label="Website or resource link (optional, HTTPS)" type="url" name="website_url" value={form.website_url} onChange={change} maxLength={2048}/><Field label="GitHub repository (optional)" type="url" name="github_url" value={form.github_url} onChange={change} maxLength={2048}/><label className="field"><span>Upload a file (optional)</span><input type="file" accept={Object.keys(types).map(x=>'.'+x).join(',')} onChange={e=>setFile(e.target.files[0]||null)}/><small>Up to 20 MB. PDF, Office documents, text, images, audio, MP4, or ZIP. Use an external link for larger files or other formats.</small></label><label className="field"><span>Sharing license</span><select name="license" value={form.license} onChange={change}>{licenses.map(l=><option key={l}>{l}</option>)}</select><small>Choose the license that applies to your work. For someone else’s work, link to the source and use its existing license.</small></label><label className="consent"><input type="checkbox" required/>I own this content or have permission to share it. It contains no private data, malware, or unlawful material.</label><button className="button" disabled={busy}>{busy?'Submitting…':'Submit for review'}</button><Notice message={message}/></form>}</>;
}
export default function Community(){const [user,setUser]=useState(null),[authReady,setAuthReady]=useState(false),[rows,setRows]=useState([]),[profile,setProfile]=useState(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[filter,setFilter]=useState('All');const path=location.pathname;
 useEffect(()=>{if(!db){setMessage('Community accounts are being configured. Please check back soon.');setLoading(false);return;}let active=true;db.auth.getSession().then(({data,error})=>{if(active){setUser(data.session?.user||null);setAuthReady(true);if(error)setMessage(error.message);}});const {data}=db.auth.onAuthStateChange((_e,s)=>{if(active){setUser(s?.user||null);setAuthReady(true);}});return()=>{active=false;data.subscription.unsubscribe();};},[]);
 useEffect(()=>{if(!db)return;let active=true;async function load(){try{let data;if(path.startsWith('/u/')){const username=decodeURIComponent(path.slice(3));const p=await result(db.from('profiles').select('*').eq('username',username).maybeSingle());if(active)setProfile(p);data=p?await readResources({author:p.id,status:'approved'}):[];}else if(path.startsWith('/resource/'))data=await readResources({id:path.slice(10)});else if(path==='/review'){if(!authReady)return;if(!user||!await result(db.rpc('moderator_status')))throw new Error('This page is for P3 moderators.');data=await readResources();}else data=await readResources({status:'approved'});if(active){setRows(data);setLoading(false);}}catch(e){if(active){setMessage(e.message);setLoading(false);}}}load();return()=>{active=false;};},[path,user?.id,authReady]);
 async function review(r,status){try{await result(db.from('submissions').update({moderation_status:status}).eq('id',r.id));setRows(await readResources());setMessage(status==='approved'?'Resource published.':'Resource is no longer public.');}catch(e){setMessage(e.message);}}
 let content;if(!db)content=<><h1>Community</h1><Notice message={message}/></>;else if(['/account','/submit'].includes(path))content=!authReady?<p role="status">Checking your session…</p>:user?(path==='/submit'?<Submit user={user}/>:<Account user={user}/>):<SignIn/>;else if(loading)content=<p role="status">Loading community…</p>;else if(path.startsWith('/u/'))content=profile?<><span className="eyebrow">P3 CONTRIBUTOR</span><div className="profile-avatar" aria-hidden="true">{profile.display_name.slice(0,1).toUpperCase()}</div><h1>{profile.display_name}</h1><p className="green">@{profile.username}</p><p className="intro description">{profile.bio}</p><h2>Shared resources</h2><Grid rows={rows}/></>:<><h1>Profile not found.</h1><a href="/community">Back to community</a></>;else if(path.startsWith('/resource/')){const r=rows[0];content=r?<><span className="eyebrow">{r.category} / {r.moderation_status}</span><h1>{r.title}</h1><Resource r={r}/><div className="description">{r.description.split('\n').map((p,i)=><p key={i}>{p}</p>)}</div><p>License: {r.license}</p>{r.file_path?<p>Files are shared by contributors. Review downloads before opening or running them.</p>:null}</>:<h1>Resource not found.</h1>;}else if(path==='/review')content=<><span className="eyebrow">MODERATION</span><h1>Keep the collection useful.</h1><p className="intro">Read the instructions, verify rights and links, and inspect files before approval. Publication makes files downloadable by anyone.</p><Grid rows={rows} review onReview={review}/></>;else content=<><section className="hero community-hero"><div><span className="eyebrow">P3 / THE COMMON GROUND</span><h1>Useful things.<br/><span className="green">Shared by people.</span></h1><p className="intro">A growing collection of projects, books, tools, and ideas. Find something that helps. Leave something that helps someone else.</p><a className="button" href="/submit">Share a resource</a></div></section><div className="section-top"><h2>From the community.</h2><label className="search"><span>Search resources</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find something useful…"/></label></div><div className="filters" role="group" aria-label="Category">{['All',...cats].map(c=><button key={c} aria-pressed={filter===c} className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}</button>)}</div><Grid rows={rows.filter(r=>(filter==='All'||r.category===filter)&&`${r.title} ${r.summary}`.toLowerCase().includes(query.toLowerCase()))}/></>;
 return <><a className="skip" href="#main">Skip to content</a><CommunityHeader/><main id="main" className="community-page">{content}<Notice message={message}/></main><footer><a href="/">PhoenixR3born</a><p>Built with curiosity. Shared with purpose.</p><a href="/account">Your space</a></footer></>;
}
