import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {loadItems,safeUrl} from './config';
import './style.css';
const categories=['All','Projects','Tools','Learning','Downloads','Recommendations','Other'];
function Mark(){return <span className="mark" aria-hidden="true">P<span>3</span></span>}
function App(){
 const [items,setItems]=useState([]),[status,setStatus]=useState('loading'),[category,setCategory]=useState('All'),[search,setSearch]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;setStatus('loading');loadItems().then(data=>{if(active){setItems(data);setStatus('ready')}}).catch(()=>{if(active)setStatus('error')});return()=>{active=false}},[attempt]);
 const slug=location.pathname.startsWith('/item/')?decodeURIComponent(location.pathname.slice(6)):null;
 const selected=slug?items.find(x=>x.slug===slug):null;
 useEffect(()=>{document.title=selected?`${selected.title} | PhoenixR3born`:'PhoenixR3born | The collection'},[selected]);
 const shown=items.filter(x=>(category==='All'||x.category===category)&&`${x.title} ${x.summary} ${x.description||''}`.toLowerCase().includes(search.toLowerCase()));
 return <><a className="skip" href="#main">Skip to content</a><header><a className="brand" href="/"><Mark/><span>Phoenix<span className="green">R3born</span><small>THE PERSONAL COLLECTION</small></span></a><nav aria-label="Main"><a href="/#collection">Collection</a><a href="https://github.com/PHONIEXz" target="_blank" rel="noopener noreferrer">GitHub</a></nav></header><main id="main">
 {slug?<section className="detail"><a className="back" href="/">Back to collection</a>{status==='loading'?<p role="status">Loading this resource…</p>:status==='error'?<ErrorState retry={()=>setAttempt(x=>x+1)}/>:selected?<><span className="eyebrow">{selected.category||'Other'}</span><h1>{selected.title}</h1><p className="intro">{selected.summary}</p>{selected.cover&&safeUrl(selected.cover)?<img className="detail-cover" src={safeUrl(selected.cover)} alt=""/>:null}<div className="description">{selected.description?.split('\n').map((line,i)=><p key={i}>{line}</p>)}</div><Actions item={selected}/><div className="share"><button onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setStatus('copied')}catch{setStatus('copy-error')}}}>Copy page link</button>{status==='copied'?<span role="status">Link copied.</span>:status==='copy-error'?<span role="status">Copy the address from your browser.</span>:null}</div></>:<><h1>Resource not found.</h1><p>It may have been removed or the link may be incomplete.</p></>}</section>:<>
 <section className="hero"><div><span className="eyebrow">BUILT. FOUND. SHARED.</span><h1>Good things.<br/><span className="green">Worth sharing.</span></h1><p>I’m Phoenix. I build things, learn cybersecurity, and share resources that can help you do more.</p><a className="button" href="#collection">Explore the collection</a></div><aside className="note"><div className="note-top"><span>FROM MY DESK</span><span>01 / R3</span></div><p>One place for what<br/>I’m working on.<br/>And what you<br/><em>should check out.</em></p><div className="note-bottom">PROJECTS / RESOURCES / DISCOVERIES</div></aside></section>
 <section id="collection" className="collection"><div className="section-top"><div><span className="eyebrow">THE COLLECTION</span><h2>Take something useful.</h2></div><label className="search"><span>Search the collection</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a resource…"/></label></div><div className="filters" role="group" aria-label="Filter by category">{categories.map(c=><button aria-pressed={category===c} key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div>
 {status==='loading'?<p className="state" role="status">Loading the collection…</p>:status==='error'?<ErrorState retry={()=>setAttempt(x=>x+1)}/>:shown.length?<div className="grid">{shown.map((item,i)=><Card item={item} index={i} key={item._id}/>)}</div>:<div className="state"><h3>{items.length?'Nothing matches yet.':'Something good is coming.'}</h3><p>{items.length?'Try another category or a different search.':'New resources will appear here when Phoenix publishes them.'}</p>{items.length?<button onClick={()=>{setCategory('All');setSearch('')}}>Clear filters</button>:null}</div>}</section></>}
 </main><footer><a className="brand" href="/"><Mark/><span>PhoenixR3born</span></a><p>Built with curiosity. Shared with purpose.</p><a href="/studio">Owner studio</a><small>© {new Date().getFullYear()} PhoenixR3born</small></footer></>
}
function ErrorState({retry}){return <div className="state" role="alert"><h3>Couldn’t load the collection.</h3><p>Please try again in a moment.</p><button onClick={retry}>Try again</button></div>}
function Actions({item}){const link=safeUrl(item.link);return <div className="actions">{link?<a className="button" href={link} target="_blank" rel="noopener noreferrer">{item.label||'Check it out'}</a>:null}{item.files?.map(f=>safeUrl(f.url)?<a className="download" key={f._key||f.url} href={`${safeUrl(f.url)}?dl=${encodeURIComponent(f.name||'download')}`} target="_blank" rel="noopener noreferrer">{f.label||f.name||'Download file'}{f.size?<small>{(f.size/1048576).toFixed(1)} MB</small>:null}</a>:null)}</div>}
function Card({item,index}){return <article className={`card tone-${index%3}`}><a href={`/item/${encodeURIComponent(item.slug)}`} className="card-art" aria-label={`Read about ${item.title}`}>{item.cover&&safeUrl(item.cover)?<img src={safeUrl(item.cover)} alt="" loading="lazy"/>:<><span className="art-label">PHOENIX / COLLECTION</span><strong>{item.title}</strong><span className="art-number">{String(index+1).padStart(2,'0')}</span></>}</a><div className="card-content"><div className="card-meta"><span>{item.category||'Other'}</span>{item.featured?<span className="featured">Phoenix’s pick</span>:null}</div><h3><a href={`/item/${encodeURIComponent(item.slug)}`}>{item.title}</a></h3><p>{item.summary}</p><a className="text-link" href={`/item/${encodeURIComponent(item.slug)}`}>See why I shared it</a></div></article>}
if(location.pathname.startsWith('/studio')){import('./studio.jsx').then(({mountStudio})=>mountStudio()).catch(()=>{createRoot(document.getElementById('root')).render(<div className="state"><h1>Studio could not load.</h1><p>Check your connection and reload the page.</p><a href="/">Back to the collection</a></div>)})}else createRoot(document.getElementById('root')).render(<App/>);
